version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codebuild-sam-test"
s3_bucket = "lswn-java-sam-test"
s3_prefix = "sam-test-codepipelin/BuildArti"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Env=\"dev\""
